### PR TITLE
Updating docs to reflect separation of repositories.

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by wking** [comment]
On Sat, Apr 04, 2015 at 10:54:34AM -0700, Greg Wilson wrote:
>   * Initial commit
>   * Importing material from lesson-template repository

These are two of the commits I dropped when cleaning up the
first-parent-ness of this branch [1].  In any case, bc47eb1 (Importing
material from lesson-template repository, 2015-03-30) and e710e14
(Merge branch 'gh-pages' of github.com:swcarpentry/lesson-example into
gh-pages, 2015-03-30) both have the same content as my fixed commit
(798cd049, README.md: Update after moving from lesson-template to
lesson-example, 2014-10-23):

  $ git show --pretty=raw bc47eb1 e710e14 798cd04  | grep tree
  tree 74ad4d7c9def85ece179eb9f20b83d1471361f70
  tree 74ad4d7c9def85ece179eb9f20b83d1471361f70
  tree 74ad4d7c9def85ece179eb9f20b83d1471361f70

To avoid the confusing history:

  $ git log --graph --topo-order --oneline --decorate example/gh-pages
  *   efda192 (example/gh-pages) Merge pull request #1 from gvwilson/updating-docs
  |\  
  | * f20afd2 Adding pointer to help to contribution instructions
  | * 2dbf7de Removing curly quotes
  | * 17222ab Removing redundant section in README
  | * 08c143c Updating based on feedback
  | * d490ba6 Updating documentation.
  | *   e710e14 Merge branch 'gh-pages' of github.com:swcarpentry/lesson-example into gh-pages
  | |\  
  | |/  
  |/|   
  * | 798cd04 (HEAD, gh-pages) README.md: Update after moving from lesson-template to lesson-example
  | *   bc47eb1 Importing material from lesson-template repository
  | |\  
  | |/  
  |/|   
  * |   f73b05c (origin/gh-pages, origin/HEAD) Merge pull request #205 from gvwilson/gh-pages
  … …

I've just rebased example/gh-pages to be:

  $ git log --graph --topo-order --oneline --decorate example/gh-pages
  *   5426365 (HEAD, example/gh-pages, gh-pages) Merge pull request #1 from gvwilson/updating-docs
  |\  
  | * 340f3e8 Adding pointer to help to contribution instructions
  | * 5c030a4 Removing curly quotes
  | * e514e54 Removing redundant section in README
  | * ebd0ed1 Updating based on feedback
  | * 3f47e26 Updating documentation.
  |/  
  * 798cd04 README.md: Update after moving from lesson-template to lesson-example
  …

Using the following procedure:

  $ git checkout -b wip f20afd2
  $ git rebase --onto 798cd04 e710e14
  $ git checkout gh-pages
  $ NAME=$(git show --pretty=format:%an example/gh-pages)
  $ EMAIL=$(git show --pretty=format:%ae example/gh-pages)
  $ DATE=$(git show --pretty=format:%ad example/gh-pages)
  $ MESSAGE=$(git show --pretty=format:%B example/gh-pages)
  $ GIT_AUTHOR_NAME="${NAME}" GIT_AUTHOR_EMAIL="${EMAIL}" GIT_AUTHOR_DATE="${DATE}" git merge -m "${MESSAGE}" --no-ff wip
  $ git branch -d wip
  $ git diff example/gh-pages  # no difference
  $ git push -f example gh-pages

[1]: Off-list discussion :(
     Subject: Re: Renaming a branch
     Date: Mon, 30 Mar 2015 10:32:32 -0700
     Message-id: <20150330173232.GW22036@odin.tremily.us>

**Comment by gvwilson** [comment]
As always, I think time spent rebasing would usually be better spent 
adding and fixing content, but I think we're just gonna have to agree to 
disagree on this...

**Comment by wking** [comment]
On Sat, Apr 04, 2015 at 11:56:18AM -0700, Greg Wilson wrote:
> As always, I think time spent rebasing would usually be better spent
> adding and fixing content, but I think we're just gonna have to
> agree to disagree on this...

It doesn't take me much time, and it makes it easier for me to
understand what's changed so I can review it.  The rebased version has
three fewer commits, so 33% fewer places that I need to look for
changes the next time I'm poking around in this part of the history.
But yeah, agree to disagree is probably where we're at ;).

**Comment by wking** [comment]
Hmm, and it looks like we missed this in review, but 340f3e814 (Adding
pointer to help to contribution instructions, 2015-04-04) is going to
make things a bit awkward for downstream lesson maintainers.  Since
it's a commit tweaking CONTRIBUTING.md on top of the version in
lesson-template, folks who create lessons based on this branch will
keep that reference (and maybe not have a “getting-and-giving-help”
section in their README.md?).  And shouldn't the target be README.md
and not README.html [1]?  Anyhow, if lesson-template updates
CONTRIBUTING.md and the downstream lesson maintainers pull those
updates, they will probably have to resolve conflicts between those
updates and 340f3e814, which seems like more trouble than the specific
link into the README is worth.  Can I reroll this branch again to drop
that edit?  Then we can add a generic link from CONTRIBUTING.md to
README.md upstream in lesson-template.

[1]: https://github.com/swcarpentry/lesson-example/blob/340f3e8149182ef26eccef196f34d0ad68a9ce49/Makefile#L7

**Pull request merged**
