### PR TITLE
Unifying links in a single file

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Put definitions of all links used in Jekyll'd Markdown pages into `_includes/links.md`.
2.  Add `{% include links.md %}` to all Jekyll'd Markdown pages.
3.  Modify `bin/lesson_check.py` to read and check this file.
4.  Modify `Makefile` to launch `bin/lesson_check.py` appropriately.

This significantly reduces duplication and inconsistency in file.  Note that:

1.  We must explicitly include `links.md` in each page - we cannot do the inclusion in the layout file because of the order in which Jekyll expands things (not even if we switch to a `.md` file in `_layouts`).
2.  We must still include all links in `CONTRIBUTING.md` and `README.md` since these are not run through Jekyll.

### CODE REVIEW

**Comment by fmichonneau** [comment]
`{% include links.md %}` should presumably also be added to the Rmd file of lesson 6

**Comment by gvwilson** [comment]
Can you please try and test?

**Comment by rgaiacs** [comment]
@fmichonneau Let me know when you test. Thanks in advance.

**Comment by gvwilson** [comment]
I've just added a test - it works fine.  Thanks for the reminder @fmichonneau - @rgaiacs, back to you.

**Comment by fmichonneau** [comment]
It looks good to me!

**Pull request merged**
