### PR TITLE
Assorted minor fixes to spelling, whitespace, hyperlinks & sorting

### PR DESCRIPTION
**Pull request by katrinleinweber**
Please see the diff and the commit messages. Nothing major

### CODE REVIEW

**Comment by rgaiacs** [comment]
@katrinleinweber Thanks. Some of the files are from https://github.com/swcarpentry/styles/ which means that the change should be done there first. I will try to copy your commits to the other repository.

**Comment by rgaiacs** [comment]
@katrinleinweber Some conflicts need to be resolve before this can be merge. Do you want to resolve the conflicts?

**Comment by katrinleinweber** [comment]
But I'm not going to repeat this work against the new repo mentioned in 10a66ed9b6b44262661f350d9bb9fccbac3acec9 by @ErinBecker. Why not clean-up the repos-to-be-migrated first by merging or closing open PRs?

**Comment by rgaiacs** [comment]
@katrinleinweber Thanks for all the work and sorry for the long time before I work on this. I had to rebase this so that I could work. I created #192 and I'm closing this.

**Comment by katrinleinweber** [comment]
OK, thanks for the info, and for taking over the rebase :-)

**Pull request closed without merging**
