### PR TITLE
Towards a more fully offline capable rendering of a lesson

### PR DESCRIPTION
**Pull request by vuw-ecs-kevin**
Basic ideas here are that:

1) Fully offline (no server required) browsing of a rendered _site directory's contents only 
    fails to work at present because of the lack of an "index.html" (or equivalent) at the end 
    of the bare URIs, which a webserver would usually, automatically, populate, eg Apache's  
   `DirectoryIndex` Directive, and so, for example,
```
    file:///path/to/_site/02-tooling/
```
   currently presents the offline user with that directory's contents, and so then they have to
   physically select  `index.html`, whereas, the ability to browse via a URI that a webserver
   would dynamically create, ie.,
```
    file:///path/to/_site/02-tooling/index.html
```
   would present the user with actual page they expect to see.

2) the lesson template's repos already contain both a `CONTRIBUTING.md` 
    and plain text `CITATION` file, but the links in the `lesson_footer.html` point
    back to the "blobs" within the remote source repo, so that content, albeit already
    there on disk in the cloned repo, is not available to the offline user browsing the 
    rendered _site.

The simple changes suggested here, which I believe require changes to both the main lesson 
example repo, and to the style repo, at the same time (submitted here as I am not sure 
as to how to go about that !) would thus:

1) add a methodology for defining a `{{ site.index }}` variable which would normally be 
    set to `index.html` but need not be. Similarly, the variable name I have chosen, `index`,
    need not be the name that SWC adopts should it want to provide this functionality.

2) make both the `Contributing` and `Cite` links in the footer point to rendered versions
   of the files already on disk in a cloned lesson 's local repo.

Here's hoping this is useful.

### CODE REVIEW

**Comment by rgaiacs** [comment]
@vuw-ecs-kevin Thanks for the pull request. It looks good to me. I added it to the "Infra" Subcommittee's list for discussion next month.

**Comment by vuw-ecs-kevin** [comment]
Could someone else run "another pair of eyes" over this conflict.

i can't actually see a conflict but it's possible I'm not looking /in the 
right places/at the right things/ ?

My two branches, gh-pages and fully-offline-capable have heads
as follows, respectively

commit fa3c636a9c7e4e5747e6673e0400658678747190

commit 3673e819ca57855425354e9fae88ccec49aa3ae9

If I do a diff (done in the filesystem to remove Git from the equation) 
on `_includes/syllabus.html` between the two, I get

```
$diff syllabus_ghp.html syllabus_foc.html 
18c18
<     <td class="col-md-3"><a href="{{ page.root }}/setup">Setup</a></td>
---
>     <td class="col-md-3"><a href="{{ page.root }}/setup/{{ site.index }}">Setup</a></td>
42c42
<         <a href="{{ page.root }}{{ episode.url }}">{{ episode.title }}</a>
---
>         <a href="{{ page.root }}{{ episode.url }}{{ site.index }}">{{ episode.title }}</a>
```
which doesn't look anything like the diffs presented in the "Resolve conflicts" display.

Have I missed something ?

**Comment by vuw-ecs-kevin** [comment]
One other thing, would I expect to be notified of the "branch has conflicts" issue via email?
If so, I don't believe I was.

**Comment by rgaiacs** [comment]
Thanks for the pull request. This was resolved at https://github.com/swcarpentry/lesson-example/pull/127.

**Pull request closed without merging**
